### ISSUE TITLE
Notes on building stack for NVIDIA Grace & Grace/Hopper

### ISSUE THREAD

**Issue by trz42** [EESSI/software-layer#967]
Issue for keeping track of what to build, in which order (coordinate among builders) and document potential issues. In general, we will follow efforts done by @bedroge building a new stack for Sapphire Rapids.

- [ ] add EasyBuild

**Comment by bedroge** [comment]
https://github.com/EESSI/docs/pull/414

Grace needs to be excluded from the software overview page v

**Comment by trz42** [comment]
> [EESSI/docs#414](https://github.com/EESSI/docs/pull/414)
> 
> Grace needs to be excluded from the software overview page v

See https://github.com/EESSI/docs/pull/415

**Comment by trz42** [comment]
Comment for installation of toolchain `foss/2023a` and all packages built with it.

**Comment by trz42** [comment]
Comment for installation of toolchain `foss/2023b` and all packages built with it.

**Comment by TopRichard** [comment]
Comment for installation of toolchain `foss/2023a` and all packages built with it.

* [x]  add GCCcore/12.3.0 grace PR:  #979 , sapphirerapids PR:  #852

**Comment by bedroge** [comment]
@TopRichard and @trz42 want to restart from scratch, so I've wiped the existing `nvidia/grace` stack.

**Comment by trz42** [comment]
Comment for installation of toolchain `foss/2022b` and all packages built with it.

Sapphire Rapids PRs to consider (incl rebuilds):
- #923 
- #927 
- #930 
- #935 
- #938 
  ```
  - Python-3.10.8-GCCcore-12.2.0-bare:
      options:
        # See https://github.com/easybuilders/easybuild-easyblocks/pull/3352
        include-easyblocks-from-commit: 1ee17c0f7726c69e97442f53c65c5f041d65c94f
  - Python-3.10.8-GCCcore-12.2.0:
      options:
        # See https://github.com/easybuilders/easybuild-easyblocks/pull/3352
        include-easyblocks-from-commit: 1ee17c0f7726c69e97442f53c65c5f041d65c94f
  ```
- #940
